# Generated by Django 5.2.3 on 2025-06-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_noteversion_options_remove_note_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='name',
            field=models.CharField(default='Untitled note', max_length=255),
        ),
    ]
