# Generated by Django 5.2.3 on 2025-06-11 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noteversion',
            options={},
        ),
    ]
